# vim:ft=ansible:
---

- name: copy files
  copy: src="{{ item }}" dest="/var/tmp/" mode="0644"
  register: file
  with_fileglob:
    - "../files/*{{ role_name }}*"
  when: ansible_distribution == "Centos"

- name: install package
  yum: name="{{ file.results[0].dest }}" state="present"
  environment:
    MDM_IP: "{{ scaleio_mdm_ips }}"
    MDM_ROLE_IS_MANAGER: "{{ node_is_manager }}"
  when: ansible_distribution == "Centos"

